# Generated by Django 4.2.5 on 2023-09-29 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.FloatField(verbose_name='цена завтрака')),
                ('diner', models.FloatField(verbose_name='цена обеда')),
                ('supper', models.FloatField(verbose_name='цена ужина')),
                ('dessert', models.FloatField(verbose_name='цена дессерта')),
            ],
            options={
                'verbose_name': 'прайс',
                'verbose_name_plural': 'прайсы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='наименование')),
                ('specific', models.CharField(blank=True, choices=[('0', 'Рыба и морепродукты'), ('1', 'Мясо'), ('2', 'Зерновые'), ('3', 'Продукты пчеловодства'), ('4', 'Орехи и бобовые'), ('5', 'Молочные продукты')], db_index=True, max_length=2, null=True, verbose_name='аллерген')),
                ('caloric', models.PositiveSmallIntegerField(verbose_name='калории')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('breakfast', models.BooleanField(default=False, verbose_name='завтрак')),
                ('diner', models.BooleanField(default=False, verbose_name='обед')),
                ('supper', models.BooleanField(default=False, verbose_name='ужин')),
                ('dessert', models.BooleanField(default=False, verbose_name='десерт')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductInReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='граммы')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='foodplan_site.product', verbose_name='продукт')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='foodplan_site.receipt', verbose_name='рецепт')),
            ],
            options={
                'verbose_name': 'продукт в рецепте',
                'verbose_name_plural': 'продукты в рецепте',
                'ordering': ['product'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(blank=True, choices=[(1, '1 месяц'), (3, '3 месяца'), (6, '6 месяцев'), (12, '12 месяцев')], db_index=True, null=True, verbose_name='период')),
                ('allergic', models.CharField(blank=True, max_length=200, null=True, verbose_name='аллергии')),
                ('breakfast', models.BooleanField(default=False, verbose_name='завтрак')),
                ('diner', models.BooleanField(default=False, verbose_name='обед')),
                ('supper', models.BooleanField(default=False, verbose_name='ужин')),
                ('dessert', models.BooleanField(default=False, verbose_name='десерт')),
                ('person', models.PositiveSmallIntegerField(default=1, verbose_name='количество персон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
