# Generated by Django 4.2.5 on 2023-09-27 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='наименование')),
                ('specific', models.CharField(blank=True, choices=[('0', 'Рыба и морепродукты'), ('1', 'Мясо'), ('2', 'Зерновые'), ('3', 'Продукты пчеловодства'), ('4', 'Орехи и бобовые'), ('5', 'Молочные продукты')], db_index=True, max_length=2, null=True, verbose_name='аллерген')),
                ('caloric', models.PositiveSmallIntegerField(verbose_name='калории')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductInReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='граммы')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='foodplan_site.product', verbose_name='продукт')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='foodplan_site.receipt', verbose_name='рецепт')),
            ],
            options={
                'verbose_name': 'продукт в рецепте',
                'verbose_name_plural': 'продукты в рецепте',
                'ordering': ['product'],
            },
        ),
    ]
