# Generated by Django 4.2.5 on 2023-09-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinreceipt',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='граммы'),
        ),
    ]
