# Generated by Django 4.2.5 on 2023-09-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='specific',
            field=models.CharField(blank=True, choices=[('0', 'Рыба и морепродукты'), ('1', 'Мясо'), ('2', 'Зерновые'), ('3', 'Продукты пчеловодства'), ('4', 'Орехи и бобовые'), ('5', 'Молочные продукты')], db_index=True, max_length=2, null=True, verbose_name='аллерген'),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
