# Generated by Django 4.2.5 on 2023-10-01 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_site', '0003_order_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promokod', models.CharField(max_length=300, verbose_name='промокод')),
                ('discount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='процент скидки')),
            ],
            options={
                'verbose_name': 'промокод',
                'verbose_name_plural': 'промокоды',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='specific',
            field=models.CharField(blank=True, choices=[('10', 'Рыба и морепродукты'), ('2', 'Мясо'), ('3', 'Зерновые'), ('4', 'Продукты пчеловодства'), ('5', 'Орехи и бобовые'), ('6', 'Молочные продукты')], db_index=True, max_length=2, null=True, verbose_name='аллерген'),
        ),
    ]
