# Generated by Django 4.2.5 on 2023-09-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_site', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='allergic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='аллергии'),
        ),
    ]
