# Generated by Django 4.2.5 on 2023-09-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_site', '0003_receipt_rename_food_product_productinreceipt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinreceipt',
            options={'ordering': ['product'], 'verbose_name': 'продукт в рецепте', 'verbose_name_plural': 'продукты в рецепте'},
        ),
    ]
