# Generated by Django 4.2.5 on 2023-10-01 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_site', '0004_promo_alter_product_specific'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='diner',
            new_name='dinner',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='процент скидки'),
        ),
    ]
