# Generated by Django 4.2.5 on 2023-09-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_site', '0004_alter_productinreceipt_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
