# Generated by Django 4.2.5 on 2023-09-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_site', '0006_alter_order_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='period',
            field=models.IntegerField(blank=True, choices=[(1, '1 месяц'), (3, '3 месяца'), (6, '6 месяцев'), (12, '12 месяцев')], db_index=True, null=True, verbose_name='период'),
        ),
    ]
