# Generated by Django 4.2.5 on 2023-09-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_site', '0007_alter_order_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.FloatField(verbose_name='цена завтрака')),
                ('diner', models.FloatField(verbose_name='цена обеда')),
                ('supper', models.FloatField(verbose_name='цена ужина')),
                ('dessert', models.FloatField(verbose_name='цена дессерта')),
            ],
            options={
                'verbose_name': 'прайс',
                'verbose_name_plural': 'прайсы',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='breakfast',
            field=models.BooleanField(default=False, verbose_name='завтрак'),
        ),
        migrations.AddField(
            model_name='order',
            name='dessert',
            field=models.BooleanField(default=False, verbose_name='десерт'),
        ),
        migrations.AddField(
            model_name='order',
            name='diner',
            field=models.BooleanField(default=False, verbose_name='обед'),
        ),
        migrations.AddField(
            model_name='order',
            name='supper',
            field=models.BooleanField(default=False, verbose_name='ужин'),
        ),
    ]
