# Generated by Django 4.2.5 on 2023-09-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_site', '0008_price_alter_order_options_order_breakfast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='person',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='количество персон'),
        ),
    ]
