# Generated by Django 4.2.5 on 2023-09-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_site', '0009_order_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='breakfast',
            field=models.BooleanField(default=False, verbose_name='завтрак'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='dessert',
            field=models.BooleanField(default=False, verbose_name='десерт'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='diner',
            field=models.BooleanField(default=False, verbose_name='обед'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='supper',
            field=models.BooleanField(default=False, verbose_name='ужин'),
        ),
    ]
